data cs; 
   infile 'H:\Stat512\Spring03\SASFiles\csdata.dat';
   input id gpa hsm hss hse satm satv genderm1;
proc print data=cs; run;
proc means data=cs maxdec=2;
   var gpa hsm hss hse satm satv;
run;
proc univariate data=cs noprint; 
   var gpa hsm hss hse satm satv;
   histogram gpa hsm hss hse satm satv /normal;
run;
options nocenter;
proc corr data=cs;
   var hsm hss hse;
proc corr data=cs noprob;
   var satm satv;
proc corr data=cs noprob;
   var hsm hss hse; 
   with satm satv;
proc corr data=cs noprob;
   var hsm hss hse satm satv;
   with gpa;
run;
proc reg data=cs; 
   model gpa=hsm hss hse;
proc reg data=cs; 
   model gpa=hsm hse;
proc reg data=cs; 
   model gpa=hsm;
proc reg data=cs; 
   model gpa=satm satv;
proc reg data=cs;
   model gpa=satm satv hsm hss hse;
   *Do general linear test;
   * test H0: beta1 = beta2 = 0;
   sat: test satm, satv;
   * test H0: beta3=beta4=beta5=0;
   hs: test hsm, hss, hse;
proc reg data=cs; 
   model gpa=hsm satm;
proc reg data=cs; 
   model gpa=hsm;
   run;
   proc reg data=a1; 
   model gpa=hsm hss hse;
run;
data cs; set cs; 
   sat=satm + satv;
proc reg data=cs;
   model gpa=sat satm satv;
run;
proc corr data=cs noprob;
	var sat satm satv;
run;
quit;