options nocenter;
data rust;
	infile 'H:\Stat512\Datasets\CH17TA02.DAT';
	input eff brand;
proc print data=rust;
* this step not necessary, could just use "brand";
data rust; set rust; 
   if brand eq 1 then abrand='A';
   if brand eq 2 then abrand='B';
   if brand eq 3 then abrand='C';
   if brand eq 4 then abrand='D';
proc print data=rust; 
proc glm data=rust; 
   class abrand; 
   model eff = abrand;
   output out=rustout r=resid;
symbol1 v=circle i=none;
proc gplot data=rustout; 
	plot (eff resid)*abrand; 
proc univariate data = rustout;
  qqplot resid / normal (L=1 mu=est sigma=est); 
run;
quit;