*NKNW100b.sas;
options nocenter;
data outlier50; 
   do x=1 to 100 by 5; 
      y=30+50*x+200*normal(0);
      output;
   end;
   x=50; y=30+50*50 +10000;
   d='out'; output;
proc print data=outlier50;
proc reg data=outlier50;
   model y=x;
   where d ne 'out';
proc reg data=outlier50;
   model y=x;
   output out=a2 r=resid;
symbol1 v=circle i=rl;
proc gplot data=a2;
   plot y*x/frame;
proc gplot data=a2;
   plot resid*x / vref=0;
quit;